name: 'tudigong Deploy Action'
description: 'Build and deploy Docker image to server'
inputs:
  stage:
    description: 'Deployment stage (dev or prd)'
    required: true
  project_name:
    description: 'Name of the project'
    required: true
  host:
    description: 'Server host'
    required: true
  user:
    description: 'Server user'
    required: true
  key:
    description: 'SSH private key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Docker availability
      shell: bash
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker is not installed or not in PATH"
          exit 1
        fi
        docker --version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      shell: bash
      run: docker buildx build --platform linux/amd64 -t ${{ inputs.project_name }}:${{ github.ref_name }}.amd64 --load .

    - name: Save Docker image to file
      shell: bash
      run: docker save ${{ inputs.project_name }}:${{ github.ref_name }}.amd64 -o ${{ inputs.project_name }}-amd64.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: ${{ inputs.project_name }}-amd64.tar

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: .


    - name: change the image permission
      shell: bash
      run: |
        chmod 644 ${{ inputs.project_name }}-amd64.tar

    - name: Transfer Docker image to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ inputs.key }}
        port: 22
        source: "${{ inputs.project_name }}-amd64.tar"
        target: "~/docker-image"

    - name: Deploy Docker image on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ inputs.key }}
        port: 22
        script: |
          set -e
          set -x
          docker load -i ~/docker-image/${{ inputs.project_name }}-amd64.tar
          rm ~/docker-image/${{ inputs.project_name }}-amd64.tar
          docker image prune -f
